---
- name: Create necessary directories
  file:
    state: directory
    path: "{{ item }}"
  with_items:
    - "{{ elasticsearch_build_path }}"

- name: Create ElasticSearch Template
  template:
    src: es.json.j2
    dest: "{{ elasticsearch_template }}"

- name: Run cloudformation
  cloudformation:
    template: "{{ elasticsearch_template }}"
    stack_name: "{{ elasticsearch_stack_name }}"
    region: "{{ region }}"
    state: "{{ elasticsearch_stack_state | default('present') }}"
    template_parameters:
      ESVersion: "{{ elasticsearch_version }}"
      ESInstanceType: "{{ elasticsearch_instance_type }}"
      ESUseEBS: "{{ elasticsearch_use_ebs }}"
      ESEBSSize: "{{ elasticsearch_ebs_size }}"
      ESEBSType: "{{ elasticsearch_ebs_type }}"
      ESEBSIOPS: "{{ elasticsearch_ebs_iops }}"
      ESDedicatedMasterEnabled: "{{ elasticsearch_dedicated_master_enabled }}"
      ESDedicatedMasterCount: "{{ elasticsearch_dedicated_master_count }}"
      ESDedicatedMasterType: "{{ elasticsearch_dedicated_master_type }}"
      ESZoneAwarenessEnabled: "{{ elasticsearch_zone_awareness_enabled }}"
      ESSnapshotHour: "{{ elasticsearch_snapshot_hour }}"
      ESInstanceCount: "{{ elasticsearch_instance_count }}"
    security_token: "{{ ansible_security_token | default(omit,true) }}"
    tags: "{{ elasticsearch_tags }}"
  register: elasticsearch_stack

- debug: var=elasticsearch_stack
